import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme/theme-provider";
import { Analytics } from "@vercel/analytics/react";
import Container from "@/components/CustomUI/container";
import Nav from "@/components/CustomUI/custom-nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-50 dark:bg-black`}>
        <ThemeProvider attribute="class" defaultTheme="system">
          <Nav />
          <Container>{children}</Container>
        </ThemeProvider>
        <Analytics />
      </body>
    </html>
  );
}
